name: "build-package-push"

on:
  push:
    branches:
      - master
    tags:

jobs:

  build-package-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm build
    - run: npm test
    - name: Publish to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: whomenope/gitbot-format
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        tag_semver: true
